# Copyright 2021 kubeflow.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: retry-random-failures
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"random-failure": [], "random-failure-2": []}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"description": "The pipeline includes
      two steps which fail randomly. It shows how to use ContainerOp(...).set_retry(...).",
      "name": "retry-random-failures"}'
spec:
  pipelineSpec:
    tasks:
    - name: random-failure
      taskSpec:
        steps:
        - name: main
          args:
          - |
            import random; import sys; exit_code = random.choice([int(i) for i in sys.argv[1].split(",")]);           print(exit_code); sys.exit(exit_code)
          - 0,1,2,3
          command:
          - python
          - -c
          image: python:alpine3.6
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "random-failure",
              "outputs": [], "version": "random-failure@sha256=04a3a3f35c930802350039b1cbf47873166a6b3c8ab9af8bfc64092c56eddf7f"}'
            tekton.dev/template: ''
      retries: 10
      timeout: 525600m
    - name: random-failure-2
      taskSpec:
        steps:
        - name: main
          args:
          - |
            import random; import sys; exit_code = random.choice([int(i) for i in sys.argv[1].split(",")]);           print(exit_code); sys.exit(exit_code)
          - 0,1
          command:
          - python
          - -c
          image: python:alpine3.6
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "random-failure",
              "outputs": [], "version": "random-failure@sha256=04a3a3f35c930802350039b1cbf47873166a6b3c8ab9af8bfc64092c56eddf7f"}'
            tekton.dev/template: ''
      retries: 5
      timeout: 525600m
  timeout: 525600m
